cantidadInversion = int(input("Ingrese la cantidad a invertir: "))
interesAnual = int(input("Ingrese el interes anual: "))
numAnos = int(input("Ingrese el numero de años: "))
capitalObt= int(cantidadInversion * (1+ float(interesAnual/100)) ** numAnos) 
print(capitalObt)